#!/bin/sh

echo "Installing Systeminfo, this may take hours...\n"
sleep 1
echo "..."
sleep 1
echo "..."
sleep 1
echo "..."
sleep 1
echo "..."
sleep 1
cp start.sh /etc/init.d/S99systeminfo
echo "Installing Systeminfo succeed, running for the first time\n"
sleep 1
/etc/init.d/S99systeminfo